In [2]:
#importing numpy
import numpy as np

In [3]:
#creating an array from list
a = np.array([0,1,2,3])
print(a)

[0 1 2 3]


In [4]:
#creating array of first 10 numbers
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [5]:
#1-Dimensional array
a = np.array([0,1,2,3])
print(a)

[0 1 2 3]


In [6]:
#printing dimensions of array
print(a.ndim)

1


In [7]:
#printing shape of array
print(a.shape)

(4,)


In [8]:
#printing length of array
print(len(a))

4


In [9]:
#2-Dimensional array
b = np.array([[0,1,2],[3,4,5]])
print(b)

[[0 1 2]
 [3 4 5]]


In [10]:
#printing dimensional of b
print(b.ndim)

2


In [11]:
#printing shape of b
print(b.shape)

(2, 3)


In [12]:
#printing length of b
#returns the size of 1st dimensional 
print(len(b))

2


In [13]:
#3-Dimensional array
c = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
print(c)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [14]:
#printing dimensional of c
print(c.ndim)

3


In [15]:
#printing shape of c
print(c.shape)

(2, 2, 2)


In [16]:
#printing length of c
print(len(c))

2


In [17]:
#creating array with range
a = np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [18]:
#creating array with range with stepsize
a = np.arange(1,10,2) #np.arange(starting_index,end_index,step_size)
print(a)

[1 3 5 7 9]


In [19]:
#creating array with linspace
b = np.linspace(0,1,6) #np.linspace(starting_index,end_index,number_of_points)
print(b)

[0.  0.2 0.4 0.6 0.8 1. ]


In [22]:
#common Arrays
#Array of ones
a = np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [25]:
#Arrays of zeros
a = np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [26]:
#Arrays of diagonal
a = np.diag([1,2,3,4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [27]:
#Create an array using random
a = np.random.rand(4)
print(a)

[0.50072614 0.58137073 0.59370065 0.04169965]


In [28]:
#Returns array with standard normalisation
a = np.random.randn(4)
print(a)

[-0.72911166  0.00503577  0.26564909 -0.3401185 ]


**The items of an array can be assigned and accessed as same way as other python sequences.**

In [29]:
#printing 5th element of an array
a = np.arange(10)
print(a[5])

5


In [30]:
a = np.diag([1,2,3])
print(a[2,2])

3


In [31]:
#assigning value to index
a = np.arange(10)
a[3] = 5
print(a)

[0 1 2 5 4 5 6 7 8 9]


In [36]:
#Slicing
a = np.arange(15)
print(a[1:8:2])  #print(array_name(starting_index:end_index:step_size))

[1 3 5 7]


In [39]:
#we can also combine assignment and slicing operation
a = np.arange(10)
print(a)
a[3:8] = 5
print(a)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 5 5 5 5 5 8 9]


In [43]:
#Element wise operation
#Basic operation 
#Addition
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a)
print(a+1)

#Subtraction
print(a-1)

#Multiplication
print(a*2)

#Division
print(a/2)

[ 1  2  3  4  5  6  7  8  9 10]
[ 2  3  4  5  6  7  8  9 10 11]
[0 1 2 3 4 5 6 7 8 9]
[ 2  4  6  8 10 12 14 16 18 20]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


In [52]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
b = np.array([11,12,13,14,15,16,17,18,19,20])
print("Subtraction of two arrays is :",a-b)
print("Addition of two arrays is :",a+b)
print("Multiplication of two array elementwise :",a*b)
print("Multiplication of two array is:",a.dot(b))
print("Division of two array is :",a/b)
print("power of 2 to the every array element",a**2)

Subtraction of two arrays is : [-10 -10 -10 -10 -10 -10 -10 -10 -10 -10]
Addition of two arrays is : [12 14 16 18 20 22 24 26 28 30]
Multiplication of two array is : [ 11  24  39  56  75  96 119 144 171 200]
Multiplication of two array is: 935
Division of two array is : [0.09090909 0.16666667 0.23076923 0.28571429 0.33333333 0.375
 0.41176471 0.44444444 0.47368421 0.5       ]
power of 2 to the every array element [  1   4   9  16  25  36  49  64  81 100]


In [56]:
#Element wise commparison
a = np.array([1,2,3,4,6])
b = np.array([3,4,3,4,5])
print(a==b)
print(a>b)
print(a<b)

[False False  True  True False]
[False False False False  True]
[ True  True False False False]


In [58]:
#Array wise comparision
a = np.array([1,2,3,4,5])
b = np.array([3,4,5,6,7])
c = np.array([1,2,3,4,5])
print(np.array_equal(a,b))
print(np.array_equal(a,c))

False
True


In [67]:
#Logical operations
a = np.array([1,1,0,0])
b = np.array([1,0,1,0])
print(np.logical_or(a,b))
print(np.logical_and(a,b))
print(np.logical_xor(a,b))
print(np.logical_not(a))

[ True  True  True False]
[ True False False False]
[False  True  True False]
[False False  True  True]


In [74]:
#Mathematical Functions
a = np.arange(10)
print("sin value of each element in array:",np.sin(a))
print("cos value of each element in array",np.cos(a))
print("tan value of each element in array",np.tan(a))
print("logarithmic value of each element in array",np.log(a))
print("exponential value of each element in array",np.exp(a))

sin value of each element in array: [ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]
cos value of each element in array [ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219
  0.96017029  0.75390225 -0.14550003 -0.91113026]
tan value of each element in array [ 0.          1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501
 -0.29100619  0.87144798 -6.79971146 -0.45231566]
logarithmic value of each element in array [      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458]
exponential value of each element in array [1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


C:\Users\dhruv\Anaconda3\envs\tensorflow_env\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in log
  


In [76]:
#basic reduction
a = np.array([1,2,3,4])
print(a)
print(np.sum(a))

[1 2 3 4]
10


In [78]:
#sum by rows and by columns
a = np.array([[1,1],[2,2]])
print(a.sum(axis=0))
print(a.sum(axis=1))

[3 3]
[2 4]


In [80]:
#minimum and maximum
a = np.array([1,2,3])
print(a.min())
print(a.max())
print(a.argmin()) #returns index of minimum element
print(a.argmax()) #returns index of maximum element

1
3
0
2


In [81]:
#all and any
print(np.all([True,False,True]))   #returns True if every element is True else returns False
print(np.all([True,True,True]))    #returns True if every element is True else returns False
print(np.any([False,False,False])) #returns True if any of element is True else returns False
print(np.any([True,False,True]))   #returns True if any of element is True else returns False

False
True
False
True


In [94]:
#statistics 
a = np.array([1,2,3,4,3,2,4,5,4,3,4,4,4,7])
b = np.array([[1,2,3,4,3,2,1,2,3],[1,2,3,3,4,45,5,6,6]])
print(np.mean(a))
print(np.median(a))
print(np.median(b,axis=1))
print(np.std(a)) 
print(a.std()) #same as np.std(a)

3.5714285714285716
4.0
[2. 4.]
1.3997084244475304
1.3997084244475304


In [104]:
#broadcasting
a = np.tile(np.arange(0,40,10),(3,1)) #np.tile(np.arange(starting_index,end_index,step_size),(number_of_rows,number_of repetations))
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
